# Generated by Django 4.2.30 on 2026-08-19 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spa', '0004_add_review_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='therapist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='therapist',
            name='working_days',
            field=models.CharField(default='1,2,3,4,5,6', max_length=50),
        ),
        migrations.AddField(
            model_name='therapist',
            name='working_hours_end',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='working_hours_start',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
