# Generated by Django 4.2.30 on 2026-07-18 01:44

from django.db import migrations, models
import invites.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address this invite is intended for.', max_length=254)),
                ('token', models.CharField(db_index=True, default=invites.utils.generate_token, help_text='Cryptographically-secure URL-safe token.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=invites.utils.get_expiry, help_text='After this timestamp the token is no longer valid.')),
                ('used_at', models.DateTimeField(blank=True, default=None, help_text='Set when the token is successfully accepted. None = unused.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
